// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EngineeringXTensions
{
    internal sealed partial class Vsix
    {
        public const string Id = "EngineeringXTensions.3a20dd24-3dda-4043-963a-726ccf3a2899";
        public const string Name = "Unity Engineering XTensions";
        public const string Description = @"A set of powerful templates, tools and extras for Unity engineers to power up your development speed and quality of life when working with Unity projects.A set of power
        https://github.com/atcarter714/UnityEngineeringXTensionsful ";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Aaron T. Carter";
        public const string Tags = "unity; game; game dev; engine; tools; templates;";
    }
}
