// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace EngineeringXTensions;
/// <summary>
/// Helper class that exposes all GUIDs used across VS Package.
/// </summary>
internal sealed partial class PackageGuids
{
	public const string EngineeringXTensionsString = "3a03143e-dbd3-4ac3-b5f8-63b21a98055b";
	public static Guid EngineeringXTensions = new Guid(EngineeringXTensionsString);
}
/// <summary>
/// Helper class that encapsulates all CommandIDs uses across VS Package.
/// </summary>
internal sealed partial class PackageIds
{
	public const int MyCommand = 0x0100;
}